export default {
ARTICLE_FETCH: "ARTICLE_FETCH",
ARTICLE_FETCH_SUCCESS: "ARTICLE_FETCH_SUCCESS",
ARTICLE_FETCH_ERROR: "ARTICLE_FETCH_ERROR",
ARTICLE_TOPIC_FETCH: "ARTICLE_TOPIC_FETCH",
ARTICLE_TOPIC_FETCH_SUCCESS: "ARTICLE_TOPIC_FETCH_SUCCESS",
ARTICLE_TOPIC_FETCH_ERROR: "ARTICLE_TOPIC_FETCH_ERROR",
ARTICLE_CLEAR_SELECTED: "ARTICLE_CLEAR_SELECTED",
}

// ARTICLE_BIAS_PLACEMENT (left center right)
// translate metrics into pics

// ARTICLE_EMOTION_FILTER
// ARTICLE_BIAS_FILTER
// ARTICLE_SENTIMENT_FILTER



