const candidates = [
    {id: 1, name: 'Bernie Sanders', party: 'Democrat', state: "Vermont", img:"", site:"", issues:"", donate:""},
    {id: 2, name: 'Michael Bennet', party: 'Democrat', state: "Colorado", img:"", site:"", issues:"", donate:""},
    {id: 3, name: 'Joseph R. Biden Jr.', party: 'Democrat', state: "Delaware", img:"", site:"", issues:"", donate:""},
    {id: 4, name: 'Michael R. Bloomberg', party: 'Democrat', state: "New York", img:"", site:"", issues:"", donate:""},
    {id: 5, name: 'Cory Booker', party: 'Democrat', state: "New Jersey", img:"", site:"", issues:"", donate:""},
    {id: 6, name: 'Pete Buttigieg', party: 'Democrat', state: "Indiana", img:"", site:"", issues:"", donate:""},
    {id: 7, name: 'Julián Castro', party: 'Democrat', state: "California", img:"", site:"", issues:"", donate:""},
    {id: 8, name: 'John Delaney', party: 'Democrat', state: "Maryland", img:"", site:"", issues:"", donate:""},
    {id: 9, name: 'Tulsi Gabbard', party: 'Democrat', state: "Hawaii", img:"", site:"", issues:"", donate:""},
    {id: 10, name: 'Kamala Harris', party: 'Democrat', state: "California", img:"", site:"", issues:"", donate:""},
    {id: 11, name: 'Amy Klobuchar', party: 'Democrat', state: "Minnesota", img:"", site:"", issues:"", donate:""},
    {id: 12, name: 'Deval Patrick', party: 'Democrat', state: "Massachusetts", img:"", site:"", issues:"", donate:""},
    {id: 13, name: 'Tom Steyer', party: 'Democrat', state: "", img:"", site:"", issues:"", donate:""},
    {id: 14, name: 'Elizabeth Warren', party: 'Democrat', state: "Massachusetts", img:"", site:"", issues:"", donate:""},
    {id: 15, name: 'Marianne Williamson', party: 'Democrat', state: "", img:"", site:"", issues:"", donate:""},
    {id: 16, name: 'Andrew Yang', party: 'Democrat', state: "", img:"", site:"", issues:"", donate:""},
    {id: 17, name: 'Donald J. Trump', party: 'Republican', state: "Florida", img:"", site:"", issues:"", donate:""},
    {id: 18, name: 'Joe Walsh', party: 'Republican', state: "Illinois", img:"", site:"", issues:"", donate:""},
    {id: 19, name: 'William F. Weld', party: 'Republican', state: "Massachusetts", img:"", site:"", issues:"", donate:""},
  ];